package ukr2lattransliteration

import "testing"

func TestTransliteration(t *testing.T) {
	tests := []struct {
		input, expected string
	}{
		{"Алушта", "Alushta"},
		{"Андрій", "Andrii"},
		{"Біла Церква", "Bila Tserkva"},
		{"Богдан", "Bohdan"},
		{"Борисенко", "Borysenko"},
		{"Борщагівка", "Borshchahivka"},
		{"Вінниця", "Vinnytsia"},
		{"Володимир", "Volodymyr"},
		{"Гадяч", "Hadiach"},
		{"Гаєвич", "Haievych"},
		{"Гаращенко", "Harashchenko"},
		{"Гоща", "Hoshcha"},
		{"Ґалаґан", "Galagan"},
		{"Ґорґани", "Gorgany"},
		{"Дмитро", "Dmytro"},
		{"Донецьк", "Donetsk"},
		{"Есмань", "Esman"},
		{"Єнакієве", "Yenakiieve"},
		{"Жанна", "Zhanna"},
		{"Жежелів", "Zhezheliv"},
		{"Житомир", "Zhytomyr"},
		{"Закарпаття", "Zakarpattia"},
		{"Згорани", "Zghorany"},
		{"Згурський", "Zghurskyi"},
		{"Знам'янка", "Znamianka"},
		{"Іванків", "Ivankiv"},
		{"Іващенко", "Ivashchenko"},
		{"Їжакевич", "Yizhakevych"},
		{"Йосипівка", "Yosypivka"},
		{"Кадиївка", "Kadyivka"},
		{"Казимирчук", "Kazymyrchuk"},
		{"Київ", "Kyiv"},
		{"Кишеньки", "Kyshenky"},
		{"Коваленко", "Kovalenko"},
		{"Короп'є", "Koropie"},
		{"Корюківка", "Koriukivka"},
		{"Костянтин", "Kostiantyn"},
		{"Лебедин", "Lebedyn"},
		{"Леонід", "Leonid"},
		{"Маринич", "Marynych"},
		{"Мар'їне", "Marine"},
		{"Медвин", "Medvyn"},
		{"Миколаїв", "Mykolaiv"},
		{"Михайленко", "Mykhailenko"},
		{"Наталія", "Nataliia"},
		{"Ніжин", "Nizhyn"},
		{"Одеса", "Odesa"},
		{"Олег", "Oleh"},
		{"Олексій", "Oleksii"},
		{"Онищенко", "Onyshchenko"},
		{"Петро", "Petro"},
		{"Полтава", "Poltava"},
		{"Решетилівка", "Reshetylivka"},
		{"Рибчинський", "Rybchynskyi"},
		{"Рівне", "Rivne"},
		{"Розгон", "Rozghon"},
		{"Соломія", "Solomiia"},
		{"Стеценко", "Stetsenko"},
		{"Стрий", "Stryi"},
		{"Суми", "Sumy"},
		{"Тернопіль", "Ternopil"},
		{"Троць", "Trots"},
		{"Ужгород", "Uzhhorod"},
		{"Уляна", "Uliana"},
		{"Фастів", "Fastiv"},
		{"Феодосія", "Feodosiia"},
		{"Філіпчук", "Filipchuk"},
		{"Харків", "Kharkiv"},
		{"Христина", "Khrystyna"},
		{"Чернівці", "Chernivtsi"},
		{"Шевченко", "Shevchenko"},
		{"Шостка", "Shostka"},
		{"Щербухи", "Shcherbukhy"},
		{"Юрій", "Yurii"},
		{"Яготин", "Yahotyn"},
		{"Ярошенко", "Yaroshenko"},
	}

	for _, tt := range tests {
		if result := Transliteration(tt.input); result != tt.expected {
			t.Errorf("Expected %s, got %s", tt.expected, result)
		}
	}
}
